import type { ProductionStyle,ProductionStyleName } from "./types";
export const PRODUCTION_STYLES:Record<ProductionStyleName,ProductionStyle>={
 "Cybersecurity Professional":{name:"Cybersecurity Professional",posterPromptStyle:"polished enterprise cybersecurity, precise and trustworthy",cameraStyle:"restrained push and slow zoom",captionStyle:"clean technical lower-third",musicStyle:"dark modern technology pulse",transitionStyle:"mostly fades",voiceStyle:"confident professional",effectsStyle:"subtle scan and interface accents"},
 "Netflix Documentary":{name:"Netflix Documentary",posterPromptStyle:"cinematic documentary, dramatic contrast and human stakes",cameraStyle:"slow cinematic drift",captionStyle:"editorial documentary",musicStyle:"cinematic investigative tension",transitionStyle:"slow cinematic dissolves",voiceStyle:"measured documentary narrator",effectsStyle:"film grain and restrained atmosphere"},
 Corporate:{name:"Corporate",posterPromptStyle:"clean premium corporate communication",cameraStyle:"stable clean push",captionStyle:"minimal corporate",musicStyle:"optimistic corporate technology",transitionStyle:"clean dissolves",voiceStyle:"executive presenter",effectsStyle:"minimal polished accents"},
 Educational:{name:"Educational",posterPromptStyle:"clear educational visual hierarchy",cameraStyle:"gentle focus-guided movement",captionStyle:"high-legibility teaching captions",musicStyle:"light minimal learning bed",transitionStyle:"soft fades",voiceStyle:"warm educator",effectsStyle:"simple explanatory highlights"},
 "Fast Social":{name:"Fast Social",posterPromptStyle:"bold high-contrast social creative",cameraStyle:"energetic pushes and pans",captionStyle:"large kinetic social captions",musicStyle:"energetic modern pulse",transitionStyle:"slides and wipes",voiceStyle:"fast conversational",effectsStyle:"punchy kinetic accents"},
 "Viral Short":{name:"Viral Short",posterPromptStyle:"scroll-stopping dramatic short-form composition",cameraStyle:"rapid focus-driven movement",captionStyle:"bold viral captions",musicStyle:"high-energy rhythmic bed",transitionStyle:"fast varied wipes",voiceStyle:"urgent hook-driven",effectsStyle:"impact hits and emphasis"},
 "News Report":{name:"News Report",posterPromptStyle:"credible broadcast news visual",cameraStyle:"controlled broadcast push",captionStyle:"broadcast lower-third",musicStyle:"restrained newsroom bed",transitionStyle:"broadcast fades",voiceStyle:"clear news presenter",effectsStyle:"clean data and ticker accents"},
};
export const DEFAULT_PRODUCTION_STYLE=PRODUCTION_STYLES["Cybersecurity Professional"];
