import { useRef, useState } from "react";
import type { Project, MusicConfiguration, MusicMode } from "../models/Project";

type Props={project:Project; projectName:string; videoDuration:number; onChange:(music:MusicConfiguration)=>void};
export function MusicDirectorPanel({project,projectName,videoDuration,onChange}:Props){
 const [message,setMessage]=useState("Ready"); const [busy,setBusy]=useState(false); const audio=useRef<HTMLAudioElement|null>(null); const music=project.music;
 const patch=(value:Partial<MusicConfiguration>)=>onChange({...music,...value});
 async function choose(mode:MusicMode){patch({mode});if(mode==="none"){patch({mode,sourcePath:null,projectPath:null,displayTitle:"",category:"",selectionReason:"Music disabled by the user."});return;}if(mode==="custom")return;setBusy(true);try{const text=[project.name,project.script,...project.slides.flatMap(s=>[s.title,s.body])].join(" ");const track=await window.cyberSlideStudio.autoSelectMusic({mode,text});patch({mode,...track,projectPath:null});setMessage(track.selectionReason||"Music selected.");}catch(e){setMessage(e instanceof Error?e.message:"Music selection failed.");}finally{setBusy(false);}}
 async function custom(){setBusy(true);try{const track=await window.cyberSlideStudio.selectCustomMusic({projectName});if(track)patch({mode:"custom",...track});}catch(e){setMessage(e instanceof Error?e.message:"Custom selection failed.");}finally{setBusy(false);}}
 function play(){stop();const source=music.projectPath||music.sourcePath;if(!source)return;audio.current=new Audio(`file:///${source.replace(/\\/g,"/")}`);void audio.current.play().catch(()=>setMessage("Preview could not play in-app; verify the local audio path."));}
 function stop(){audio.current?.pause();audio.current=null;}
 async function prepare(){setBusy(true);try{const result=await window.cyberSlideStudio.prepareMusicAudio({projectName,config:music,narrationPath:project.voiceover.narrationPath,durationSeconds:videoDuration||project.voiceover.totalDurationSeconds});onChange(result);setMessage(`Audio prepared: ${result.finalMixPath}`);}catch(e){setMessage(e instanceof Error?e.message:"Audio preparation failed.");}finally{setBusy(false);}}
 return <div className="director-panel"><p className="eyebrow">MUSIC DIRECTOR</p><h2>Project Soundtrack</h2><label>Music mode<select value={music.mode} onChange={e=>void choose(e.target.value as MusicMode)}><option value="auto-match">Auto Match</option><option value="auto-rotate">Auto Rotate</option><option value="custom">Custom Track</option><option value="none">No Music</option></select></label><div className="music-summary"><strong>{music.displayTitle||"No track selected"}</strong><span>{music.category||"—"} · {music.durationSeconds?`${music.durationSeconds.toFixed(1)} sec`:"Unknown duration"}</span><p>{music.selectionReason||"Choose a mode to select music."}</p></div><div className="inspector-grid"><label>Gain<input type="number" min="0" max="1" step="0.01" value={music.gain} onChange={e=>patch({gain:Number(e.target.value)})}/></label><label>Ducking amount<input type="number" min="0" max="1" step="0.05" value={music.duckingAmount} onChange={e=>patch({duckingAmount:Number(e.target.value)})}/></label><label>Fade in<input type="number" min="0" max="10" step="0.1" value={music.fadeInSeconds} onChange={e=>patch({fadeInSeconds:Number(e.target.value)})}/></label><label>Fade out<input type="number" min="0" max="10" step="0.1" value={music.fadeOutSeconds} onChange={e=>patch({fadeOutSeconds:Number(e.target.value)})}/></label></div><label><input type="checkbox" checked={music.duckingEnabled} onChange={e=>patch({duckingEnabled:e.target.checked})}/> Duck under narration</label><div className="panel-action-grid"><button onClick={play} disabled={!music.sourcePath&&!music.projectPath}>Preview / Play</button><button onClick={stop}>Stop</button><button onClick={()=>void window.cyberSlideStudio.scanMusicLibrary().then(r=>setMessage(`${r.tracks.length} tracks found.`))}>Rescan Library</button><button onClick={()=>void custom()}>Select Custom Track</button><button className="primary-button" onClick={()=>void prepare()} disabled={busy||(!videoDuration&&!project.voiceover.totalDurationSeconds)}>Prepare Audio</button><button onClick={()=>patch({sourcePath:null,projectPath:null,displayTitle:"",category:"",durationSeconds:0,selectionReason:"",lastPreparedAt:null,finalMusicPath:null,finalMixPath:null})}>Clear Selection</button></div><button className="ghost-button" onClick={()=>void window.cyberSlideStudio.openMusicLibrary()}>Open Music Library</button><div className="operation-status">{busy?"Working…":message}</div></div>;
}
