const { app } = require("electron");
const fs = require("node:fs/promises");
const path = require("node:path");
const { spawn } = require("node:child_process");
const { resolveFfmpeg } = require("../video/ffmpegResolver.cjs");

const CATEGORIES = ["Corporate", "Dark Cyber", "Documentary", "Energetic", "Inspirational", "Minimal", "Technology"];
const EXTENSIONS = new Set([".mp3", ".wav", ".m4a", ".aac", ".flac"]);
function libraryRoot() { return path.join(__dirname, "..", "..", "Music Library"); }
async function ensureLibrary() { const root=libraryRoot(); await Promise.all(CATEGORIES.map(c=>fs.mkdir(path.join(root,c),{recursive:true}))); return root; }
function safeAudio(filePath) { const ext=path.extname(String(filePath||"")).toLowerCase(); if(!EXTENSIONS.has(ext)) throw new Error("Choose an MP3, WAV, M4A, AAC, or FLAC audio file."); return path.resolve(filePath); }
function categoryForText(value) {
 const text=String(value||"").toLowerCase();
 const scores={Corporate:0,"Dark Cyber":0,Documentary:0,Energetic:0,Inspirational:0,Minimal:0,Technology:0};
 const words={Corporate:["business","enterprise","company","professional","policy"],"Dark Cyber":["breach","attack","threat","ransomware","hacker","dark","phishing"],Documentary:["history","story","explains","investigation","truth","why"],Energetic:["fast","urgent","warning","action","now","critical"],Inspirational:["success","future","confidence","empower","better","protect"],Minimal:["simple","basics","guide","tips","habit"],Technology:["technology","cyber","digital","data","ai","software","password"]};
 for(const [category,keys] of Object.entries(words)) for(const key of keys) if(text.includes(key)) scores[category]+=1;
 return Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][1] ? Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0] : "Technology";
}
function run(exe,args){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{windowsHide:true,shell:false});let err="";child.stderr.on("data",d=>err+=d);child.once("error",reject);child.once("close",c=>c===0?resolve(err):reject(new Error(`FFmpeg exited with code ${c}. ${err.slice(-1200)}`)));});}
async function duration(filePath){const ff=await resolveFfmpeg();try{const text=await run(ff.path,["-hide_banner","-i",filePath,"-f","null","-"]);const m=text.match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):0;}catch(error){const m=String(error.message).match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);if(m)return Number(m[1])*3600+Number(m[2])*60+Number(m[3]);throw error;}}
async function scanLibrary(){const root=await ensureLibrary();const tracks=[];for(const category of CATEGORIES){const dir=path.join(root,category);for(const entry of await fs.readdir(dir,{withFileTypes:true})){if(!entry.isFile()||!EXTENSIONS.has(path.extname(entry.name).toLowerCase()))continue;const filePath=path.join(dir,entry.name);tracks.push({sourcePath:filePath,displayTitle:path.parse(entry.name).name,category,durationSeconds:await duration(filePath).catch(()=>0)});}}return {root,categories:CATEGORIES,tracks};}
async function readRecent(){try{return JSON.parse(await fs.readFile(path.join(app.getPath("userData"),"music-recent.json"),"utf8"));}catch{return [];}}
async function remember(filePath){const recent=(await readRecent()).filter(x=>x!==filePath);recent.unshift(filePath);await fs.writeFile(path.join(app.getPath("userData"),"music-recent.json"),JSON.stringify(recent.slice(0,20),null,2));}
function chooseRotated(candidates,recent){const fresh=candidates.filter(t=>!recent.includes(t.sourcePath));return fresh.length?fresh:candidates;}
function buildAudioPlan(config,total){return {durationSeconds:Number(total),fadeOutStart:Math.max(0,Number(total)-Number(config.fadeOutSeconds||0)),gain:Number(config.gain??0.18),duckingEnabled:Boolean(config.duckingEnabled)};}
async function selectTrack({mode,text}){if(mode==="none")return null;const scan=await scanLibrary();if(!scan.tracks.length)throw new Error(`Music Library is empty. Add supported audio files under ${scan.root}.`);const category=categoryForText(text);let candidates=scan.tracks.filter(t=>t.category===category);let reason=`Matched ${category} to the project's language and tone.`;if(!candidates.length){candidates=scan.tracks;reason=`${category} was the best match, but that category is empty; selected an available library track.`;}if(mode==="auto-rotate"){const recent=await readRecent();candidates=chooseRotated(candidates,recent);reason=`Rotated away from recently used tracks${category?` in ${category}`:""}.`; }const track=candidates[0];await remember(track.sourcePath);return {...track,selectionReason:reason};}
async function copyCustom(sourcePath,audioRoot){const safe=safeAudio(sourcePath);const stat=await fs.stat(safe);if(!stat.isFile())throw new Error("The selected music path is not a file.");await fs.mkdir(audioRoot,{recursive:true});const target=path.join(audioRoot,`CustomTrack${path.extname(safe).toLowerCase()}`);await fs.copyFile(safe,target);return {sourcePath:safe,projectPath:target,displayTitle:path.parse(safe).name,category:"Custom",durationSeconds:await duration(target),selectionReason:"Custom track selected by the user."};}
async function prepareAudio({config,audioRoot,narrationPath,durationSeconds}){const total=Number(durationSeconds);if(!Number.isFinite(total)||total<=0)throw new Error("A valid final video duration is required before preparing audio.");await fs.mkdir(audioRoot,{recursive:true});const ff=await resolveFfmpeg();const musicPath=config.projectPath||config.sourcePath;const finalMusic=path.join(audioRoot,"FinalMusic.wav");const finalMix=path.join(audioRoot,"FinalMix.wav");const fadeOut=Math.max(0,total-Number(config.fadeOutSeconds||0));if(config.mode!=="none"){safeAudio(musicPath);await fs.access(musicPath);await run(ff.path,["-y","-stream_loop","-1","-i",musicPath,"-t",String(total),"-af",`loudnorm=I=-23:TP=-2:LRA=11,volume=${Number(config.gain??0.18)},afade=t=in:st=0:d=${Number(config.fadeInSeconds||0)},afade=t=out:st=${fadeOut}:d=${Number(config.fadeOutSeconds||0)}`,"-ar","48000","-ac","2",finalMusic]);}
 if(narrationPath){await fs.access(narrationPath);if(config.mode==="none"){await run(ff.path,["-y","-i",narrationPath,"-t",String(total),"-af","loudnorm=I=-16:TP=-1.5:LRA=11,alimiter=limit=0.95","-ar","48000","-ac","2",finalMix]);}else{const filter=config.duckingEnabled?`[0:a]loudnorm=I=-16:TP=-1.5:LRA=11[n];[1:a][n]sidechaincompress=threshold=0.02:ratio=8:attack=20:release=300[duck];[n][duck]amix=inputs=2:duration=longest,alimiter=limit=0.95[out]`:`[0:a]loudnorm=I=-16:TP=-1.5:LRA=11[n];[n][1:a]amix=inputs=2:duration=longest,alimiter=limit=0.95[out]`;await run(ff.path,["-y","-i",narrationPath,"-i",finalMusic,"-filter_complex",filter,"-map","[out]","-t",String(total),"-ar","48000","-ac","2",finalMix]);}}else if(config.mode!=="none")await fs.copyFile(finalMusic,finalMix);else throw new Error("No narration or music is available to prepare.");
 const preparedAt=new Date().toISOString();const selected={...config,lastPreparedAt:preparedAt,finalMusicPath:config.mode==="none"?null:finalMusic,finalMixPath:finalMix};await fs.writeFile(path.join(audioRoot,"SelectedTrack.json"),JSON.stringify(selected,null,2));await fs.writeFile(path.join(audioRoot,"AudioReport.json"),JSON.stringify({preparedAt,durationSeconds:total,narrationPath:narrationPath||null,musicPath:config.mode==="none"?null:musicPath,finalMixPath:finalMix,duckingEnabled:Boolean(config.duckingEnabled)},null,2));return selected;}
module.exports={CATEGORIES,EXTENSIONS,buildAudioPlan,categoryForText,chooseRotated,copyCustom,ensureLibrary,prepareAudio,scanLibrary,selectTrack};

