import type { LayoutTemplateId } from "./LayoutTemplates";
export const EDITORIAL_PACKAGE_VERSION="1.0.0";
export type EditorialPackage={displayHeadline:string;highlightPhrase:string;supportLine:string;narration:string;posterPrompt:string;motionHint:string;captionHint:string;layoutTemplate:LayoutTemplateId;headlineScale:number;supportScale:number;manuallyEdited:boolean;generatedAt:string;version:string};
const clean=(v:string)=>String(v||"").replace(/\s+/g," ").trim(),words=(v:string)=>clean(v).split(/\s+/).filter(Boolean),norm=(v:string)=>clean(v).toLowerCase().replace(/[^\p{L}\p{N}'’]+/gu," ").trim();
const chooseHighlight=(headline:string)=>{const list=words(headline.replace(/\n/g," "));return list.slice(-Math.min(3,list.length)).join(" ")||"FOCUS"};
const headlineFrom=(title:string)=>words(title).filter(word=>!/^(IN|A|THE|TO)$/i.test(word)).slice(0,8).join(" ").toUpperCase()||"UNTITLED STORY";
const intentionalBreaks=(headline:string,highlight:string)=>{const list=words(headline),accent=words(highlight),start=list.findIndex((_,i)=>accent.every((word,j)=>norm(list[i+j]||"")===norm(word)));if(start>0&&start+accent.length===list.length)return [list.slice(0,start).join(" "),list.slice(start).join(" ")].filter(Boolean).join("\n");const midpoint=Math.ceil(list.length/2);return [list.slice(0,midpoint).join(" "),list.slice(midpoint).join(" ")].filter(Boolean).join("\n")};
const supportFrom=(body:string)=>{const sentence=(clean(body).split(/(?<=[.!?])\s+/)[0]||body).replace(/[.!?]+$/,"").replace(/\bOne\b/i,"A single").replace(/\bcan\b/i,"may").replace(/\bevery\b/i,"each");const list=words(sentence);return `${list.slice(0,16).join(" ")}${list.length?".":""}`};
export function generateEditorialPackage(input:{title:string;body:string;cta?:string;layoutTemplate?:LayoutTemplateId;posterPrompt?:string;motionHint?:string;captionHint?:string}):EditorialPackage{const raw=headlineFrom(input.title),highlight=chooseHighlight(raw),displayHeadline=intentionalBreaks(raw,highlight),supportLine=supportFrom(input.body),narration=[clean(input.body),clean(input.cta||"")].filter(Boolean).join(" ");return {displayHeadline,highlightPhrase:highlight,supportLine,narration,posterPrompt:clean(input.posterPrompt||`A concrete cinematic vertical scene illustrating ${clean(input.title)||"the slide topic"}.`),motionHint:clean(input.motionHint||"Slow cinematic push"),captionHint:clean(input.captionHint||"Emphasize the key spoken consequence"),layoutTemplate:input.layoutTemplate||"editorial-left",headlineScale:1,supportScale:1,manuallyEdited:false,generatedAt:new Date().toISOString(),version:EDITORIAL_PACKAGE_VERSION}}
export function validateEditorialPackage(pkg:EditorialPackage):string[]{const errors:string[]=[];if(words(pkg.displayHeadline).length>8)errors.push("Display Headline exceeds eight words.");if(!clean(pkg.highlightPhrase))errors.push("Highlight phrase is required.");const headlineTokens=words(pkg.displayHeadline).map(norm),highlightTokens=words(pkg.highlightPhrase).map(norm);if(!headlineTokens.some((_,i)=>highlightTokens.every((word,j)=>headlineTokens[i+j]===word)))errors.push("Highlight phrase must appear in Display Headline.");if(!clean(pkg.narration))errors.push("Narration is required.");if(norm(pkg.supportLine)===norm(pkg.displayHeadline)||norm(pkg.displayHeadline).includes(norm(pkg.supportLine)))errors.push("Support Line duplicates Display Headline.");return errors}
export function migrateEditorialPackage(slide:{title:string;body:string;cta:string;layoutTemplateId:LayoutTemplateId;editorial?:{displayHeadline?:string;emphasizedText?:string;supportingLine?:string;headlineSize?:number;supportSize?:number;manualOverride?:boolean}|null},value?:unknown):EditorialPackage{if(value&&typeof value==="object"){const pkg=value as EditorialPackage;return {...generateEditorialPackage({title:slide.title,body:slide.body,cta:slide.cta,layoutTemplate:slide.layoutTemplateId}),...pkg,manuallyEdited:pkg.manuallyEdited===true}}const generated=generateEditorialPackage({title:slide.title,body:slide.body,cta:slide.cta,layoutTemplate:slide.layoutTemplateId});if(slide.editorial?.displayHeadline)return {...generated,displayHeadline:slide.editorial.displayHeadline,highlightPhrase:slide.editorial.emphasizedText||generated.highlightPhrase,supportLine:slide.editorial.supportingLine||generated.supportLine,headlineScale:(slide.editorial.headlineSize||138)/138,supportScale:(slide.editorial.supportSize||44)/44,manuallyEdited:slide.editorial.manualOverride===true};return generated}