import { useEffect, useState } from "react";
import type { Project } from "../models/Project";
import type { Slide } from "../models/Slide";
import { slideLayoutFingerprint } from "../editorial/LayoutFreshness";
type Props={project:Project;slideId:string;reviewSlideIds:string[];onSelect:(id:string)=>void;onApprove:(slide:Slide)=>Promise<void>;onRegenerate:(slide:Slide)=>Promise<void>;onKeep:(slide:Slide)=>void;onEdit:()=>void;onClose:()=>void};
const bounds=(v:{x:number;y:number;width:number;height:number})=>({left:`${v.x/10.8}%`,top:`${v.y/19.2}%`,width:`${v.width/10.8}%`,height:`${v.height/19.2}%`});
export function WorkingImageReview({project,slideId,reviewSlideIds,onSelect,onApprove,onRegenerate,onKeep,onEdit,onClose}:Props){
 const slide=project.slides.find(x=>x.id===slideId)||project.slides[0],[workingUrl,setWorkingUrl]=useState<string|null>(null),[approvedUrl,setApprovedUrl]=useState<string|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState<"working"|"approved">("working");
 useEffect(()=>{let alive=true;void(async()=>{try{if(slide.background.workingImagePath){const data=await window.cyberSlideStudio.readSlideImage(slide.background.workingImagePath);if(alive)setWorkingUrl(data)}if(slide.background.approvedImagePath){const data=await window.cyberSlideStudio.readSlideImage(slide.background.approvedImagePath);if(alive)setApprovedUrl(data)}}catch(e){if(alive)setError(e instanceof Error?e.message:"Image file could not be loaded.")}})();return()=>{alive=false}},[slide.id,slide.background.workingImagePath,slide.background.approvedImagePath]);
 useEffect(()=>{document.querySelector(`[data-review-slide="${slide.id}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})},[slide.id]);
 const pending=project.slides.filter(x=>x.background.workingImagePath&&x.workingImageFingerprint!==x.approvedImageFingerprint),failed=project.slides.filter(x=>x.layoutWarnings.some(w=>/fail|error/i.test(w))),status=!slide.background.approvedImagePath?(slide.background.workingImagePath?"WORKING — REVIEW NEEDED":"NO IMAGE"):(slide.workingImageFingerprint!==slide.approvedImageFingerprint?"WORKING — REVIEW NEEDED":slide.approvedImageFingerprint===slideLayoutFingerprint(slide)?"APPROVED":"STALE"),plan=slide.compositionPlan,index=reviewSlideIds.indexOf(slide.id);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"Review action failed.")}finally{setBusy(false)}};
 const visual=(url:string|null,label:string)=><div className="review-visual"><strong>{label}</strong><div className="layout-preview-frame">{url?<img src={url} alt={`${label} for slide ${slide.number}`}/>:<div className="missing-review-image">No image</div>}{plan&&<><div className="review-zone editorial" style={bounds(plan.textZone)}>Editorial text zone</div><div className="review-zone subject" style={bounds(plan.subjectZone)}>Subject zone</div><div className="review-zone captions" style={bounds(plan.captionZone)}>Caption-safe zone</div></>}<div className="review-editorial-copy"><h3>{slide.editorial?.displayHeadline||slide.title}</h3><em>{slide.editorial?.emphasizedText}</em><p>{project.slideTextOverlay.enabled?slide.editorial?.supportingLine:""}</p></div></div></div>;
 return <main className="working-review"><header><div><p className="eyebrow">IMAGE REVIEW</p><h1>Working Image Review</h1><p>Layout Preview — Not Final Video</p></div><button className="ghost-button" onClick={onClose}>Back to Project</button></header><div className="review-summary"><span>Approved: {project.slides.filter(x=>x.background.approvedImagePath).length}</span><span>Working awaiting review: {pending.length}</span><span>Failed: {failed.length}</span></div><div className="review-metadata"><strong>Slide {slide.number}</strong><span className="review-badge">{status}</span><span>Layout: {slide.layoutTemplateId}</span><span>Generated: {slide.workingGeneratedAt?new Date(slide.workingGeneratedAt).toLocaleString():"Unknown"}</span><span>Validation: {slide.compositionValidation?.accepted?"Passed":"Needs review"}</span></div><div className="review-tabs"><button className={tab==="approved"?"active":""} onClick={()=>setTab("approved")}>Current Approved</button><button className={tab==="working"?"active":""} onClick={()=>setTab("working")}>New Working</button></div><div className={`review-comparison tab-${tab}`}>{visual(approvedUrl,"Current Approved")}{visual(workingUrl||approvedUrl,"New Working")}</div>{!workingUrl&&slide.background.approvedImagePath&&<div className="review-warning">No Working image exists. Previewing proposed layout over Approved; composition may not match until regenerated.</div>}<dl className="review-paths"><dt>Working file</dt><dd>{slide.background.workingImagePath||"None"}</dd><dt>Approved file</dt><dd>{slide.background.approvedImagePath||"None"}</dd></dl>{slide.layoutWarnings.length>0&&<div className="review-warning"><strong>Composition warnings</strong><ul>{slide.layoutWarnings.map(w=><li key={w}>{w}</li>)}</ul></div>}{error&&<div className="review-error">{error}</div>}<div className="review-actions"><button className="primary-button" disabled={busy||!workingUrl} onClick={()=>void act(()=>onApprove(slide))}>Approve Replacement</button><button className="secondary-button" disabled={busy} onClick={()=>void act(()=>onRegenerate(slide))}>Regenerate Again</button><button className="secondary-button" disabled={busy} onClick={onEdit}>Edit Layout</button><button className="secondary-button" disabled={busy} onClick={()=>onKeep(slide)}>Keep Existing Approved</button><button className="secondary-button" onClick={()=>void window.cyberSlideStudio.openWorkingFolder(project.name)}>Open Working Folder</button></div><div className="review-slide-strip">{reviewSlideIds.map(id=>{const item=project.slides.find(x=>x.id===id);return item?<button key={id} data-review-slide={id} className={id===slide.id?"active":""} onClick={()=>onSelect(id)}>Slide {item.number}<small>{item.workingImageFingerprint!==item.approvedImageFingerprint?"REVIEW NEEDED":"APPROVED"}</small></button>:null})}</div>{index>=0&&<p>Reviewing {index+1} of {reviewSlideIds.length}</p>}</main>;
}